### PR TITLE
feat: user group pings

### LINKED ISSUE #3: User group pings
Ping a user group **in another message**. Include text about not replying to that message. Set the `text` field to the mrkdwn, so that notifications show the update.

### PR DESCRIPTION
**Pull request by NeonGamerBot-QK**
Fixes #3 
uses an ENV var so make sure to update code accordingly

### CODE REVIEW

**Review by skyfallwastaken — CHANGES_REQUESTED** [review]
Please don't use process.env here - instead add it to the `Env` Zod schema as a z.string(), then use env.SLACK_SUBTEAM_ID

**Review by skyfallwastaken — CHANGES_REQUESTED** [review]
Please add it to the Env schema at the top of the file as a z.string()

**Comment by skyfallwastaken** [comment]
LGTM, I'll merge + announce once I get home and can update the env variable. Thanks!

**Review by skyfallwastaken — APPROVED** [review]

**Comment by SkyfallWasTaken** [comment]
LGTM, I'll merge + announce once I get home and can update the env variable. Thanks!

**Pull request merged**
