### PR TITLE
update: change url to dev

### PR DESCRIPTION
**Pull request by NeonGamerBot-QK**
note: prob update the cookie

### CODE REVIEW

**Comment by skyfallwastaken** [comment]
What's the reason for this change? /genq

**Comment by skyfallwastaken** [comment]
Also, plz update the version in package.json

**Comment by NeonGamerBot-QK** [comment]
> What's the reason for this change? /genq

it will get the dev shop changes before pushed for main (if the dev works like that i think)

**Comment by skyfallwastaken** [comment]
Pretty sure they both use the same Airtable base, so it wouldn't be able to get the changes quicker :/

**Comment by NeonGamerBot-QK** [comment]
damn, ill close this then

**Comment by skyfallwastaken** [comment]
sorry for wasting your time :/

**Pull request closed without merging**
